### ISSUE TITLE
No Maintainer - What to do?

### ISSUE THREAD

**Issue by kaeawc** [Raizlabs/DBFlow#351] opened 2015-08-06 13:06 UTC
Making this issue so we can have a discussion.

There doesn't seem to be an active maintainer at Raizlabs anymore for this project, @agrosner hasn't responded in quite some time and neither has @arrouse. If you look at commits to `master` and `develop` the only thing that has changed was an update to the license file 13 days ago. In the meantime there are some critical issues that users are reporting, and as one of those users, I would like to fix them.

Is there any interest in contributing to the project? Should we fork it? Raizlabs does have a copyright license on the project and I want to respect that, but if we make a fork we would have to make our own maven repository on JCenter under a different group as we would not have permission to upload releases (Unless someone at Raizlabs allows new contributors to do so).

Mentioning [past contributors](https://github.com/Raizlabs/DBFlow/graphs/contributors) so they can see this -- sorry if this is spammy.

@mcumings
@kamilzych
@dylanrjames
@mozarcik
@wongcain
@ktzouno
@mathieudebrito
@MaciejCiemiega
@mickele
@kayvannj
@intrications
@pplant
@MoranM
@martino2k6
@noughts
@jan-pintr

**Comment by fabiendem** [comment] 2015-08-06 13:44
Wasn't @agrosner simply on holidays? (https://twitter.com/agrosner)
But more external contributions can't be bad for the library!

**Comment by kaeawc** [comment] 2015-08-06 13:55
If that's the case my apologies :x

**Comment by octohub** [comment] 2015-08-06 15:04
@kaeawc love that you called this meeting and want to make sure DBFlow is still alive. I can tell you that it is! @agrosner has been on vacation and there are plans to continually improve DBFlow.

**Comment by mathieudebrito** [comment] 2015-08-06 15:06
@octohub Good to hear !

**Comment by kaeawc** [comment] 2015-08-06 15:55
Sweet :fireworks:

**Comment by ydanneg** [comment] 2015-08-07 19:55
Other contributors also on holidays? That's the problem. The problem is that nobody can't fix this and make a decision on the resolution. We need community.

**Comment by graiz** [comment] 2015-08-08 05:09
Thanks for the comments. We do intend to maintain the repo and provide community. We've been a little busy with Android requests as a result we've been slow to respond but we are trying to address this. If anyone here is interested in being a more active maintainer... we are hiring at Raizlabs..  :)

**Comment by agrosner** [comment] 2015-08-10 11:35
@kaeawc thanks for the issue. I have been on vacation, changed jobs, and have been very busy past few weeks. 

Unfortunately, since I do not work at Raizlabs anymore, I cannot continue working on this library in the same fashion as I have before. I do not have permission to close issues, review pull requests, or upload releases myself. Which is a shame since I worked on the project at least 90% on my own time. That said, I do believe in @octohub to help me and let me push code for him to review and merge. I just won't be able to push out updates or releases without someone at Raizlabs doing so.

I strongly wish to support you guys going forward, but keep in mind that it won't be in the same capacity unless Raizlabs transfers the repo to me. 

- Andrew

**Comment by Rainer-Lang** [comment] 2015-08-10 13:11
That are no good news...on the one hand...on the other......
I hope your new job is fine and the vacation was relaxing.

**Comment by Rainer-Lang** [comment] 2015-08-11 15:33
@Raizlabs What are your plans with this lib?

**Comment by mlebarron** [comment] 2015-08-11 18:41
Thanks for bringing this up, and apologies for the lack of communication as of late. We certainly want to be responsive. 

Open Source is important, as is the community around it, and we strongly believe that. I chatted briefly with @agrosner today, so I can confirm he’s back from vacation. We are working this week on how to make sure both the library and community can continue long term, and in the short term to make sure that some of the critical issues are being addressed. 

Additionally, we are exploring having external contributors and are looking at ways to be more responsive to pull requests. If have specific concerns or you are interested in helping out please email me: michael.lebarron@raizlabs.com

-Michael LeBarron, Director of Engineering @ Raizlabs

**Comment by ydanneg** [comment] 2015-08-11 19:01
Thanks for a response.

I'd like to suggest creating the mailing list (group) to discuss Design
decisions and other technical issues, just keeping bug tracker for bug
reports only.

PS.
I personally see DBFlow as the best ORM for Android these days. Good work.
Let's make it main stream.

Gennadi Kudrjavtsev

**Comment by kaeawc** [comment] 2015-08-11 20:45
Yeah, its definitely the best that I've found, want to keep making it better.

Google groups might work best?

**Comment by mlebarron** [comment] 2015-08-13 15:23
Hey all, I've started a google group so general discussion doesn't have to happen via github issues.

https://groups.google.com/forum/?hl=en#!forum/dbflow

**Comment by mlebarron** [comment] 2015-08-13 15:45
Closing so this can move out of github issues

**Closed by mlebarron** 2015-08-13 15:45 UTC

**Comment by agrosner** [comment] 2015-08-19 13:56
Anyone still tracking this issue, I have been reinstated as a full maintainer going forward and have some great plans for this library. Will post something on google groups.
