### ISSUE TITLE
4.0.2 Operator.notIn is creating a new Object array instead of casting.

### ISSUE THREAD

**Issue by NightlyNexus** [Raizlabs/DBFlow#1309] opened 2017-06-01 20:30 UTC
https://github.com/Raizlabs/DBFlow/blob/4.0.2/dbflow/src/main/java/com/raizlabs/android/dbflow/sql/language/Operator.java#L389
This line appears correct, but, from debugging, I see that this line in the jitpack 4.0.2 release is actually: `return new Operator.In(this, firstBaseModelQueriable, false, new Object[]{baseModelQueriables});`

This, of course, causes SQLiteDatatypeMismatchExceptions.
I'm concerned that the tagged release and the release on jitpack are not the same. Hopefully I'm wrong.

**Comment by agrosner** [comment] 2017-06-02 02:22
dupe of #1293

**Closed by agrosner** 2017-06-02 02:22 UTC

**Comment by NightlyNexus** [comment] 2017-06-02 02:26
Ah, sorry about that. https://github.com/Raizlabs/DBFlow/commit/8cd8dc2828f59811e0e41550ba164d75e66e99fc
Thanks!
