### ISSUE TITLE
Update DB failed - duplicate column

### ISSUE THREAD

**Issue by Informaticore** [Raizlabs/DBFlow#337] opened 2015-07-23 10:28 UTC
I want to migrate my App Databse from version 2 to version 3.
While the database is in version 2 I added a new Model "Test".
Then I added a new Column in version 3 and used the migrations addColumn().

If I update the installed App with database version 2 to 3 everything is working. 
But if I update an installed App with database version 1 to 3 the mirgation failed with:  

Upgrading Database from 1 to 3
I/Database﹕ Executing Migration: x.x.x.database.migrations: AddTestColumn
E/SQLiteLog﹕ (1) duplicate column name: test2

This means, that the Model-Table is created with all its columns and then it tries to run the migrations with addColumn(). 

Isn't adding a Model be versioned as well?

**Comment by kzsolti** [comment] 2015-07-23 10:55
I'm currently working on integrating DBFlow into my app, and this is something I also noticed while planning my initial migration, and wanted to investigate further.

Tables are most definitely created in their current state if they don't exist in the database, that's for sure. Based on the source of FlowSQLiteOpenHelper, I made two observations:
* when updating the database, DBFlow will run the migrations from the current version to the latest version - this behavior seems correct
* when creating a new database, DBFlow will also run migrations - this is because of the support for an initial migration identified with 'version 0' - but it will also run all migration to the latest version!

I believe that if I'm right, then this behavior when creating a new database is wrong. Creation of the database should always be kept up-to-date, and include everything that is necessary to initialize the schema and content during the automatic table and view creation and in the initial version 0 migration. Any migration after that should only be incremental changes to upgrade existing databases.

I will create some test to confirm this, hopefully I'll have some time later today or tomorrow. I think the fix may be simple enough if I'm right, so I might create a pull request as well.

**Comment by kzsolti** [comment] 2015-07-24 15:16
Okay, I did some tests, and I must say that I was wrong.

While DBFlow calls its internal ```executeMigrations``` with the current version as ```db.getVersion()``` when creating a new database, the version of the database supplied by that call is always 0 even if the database is created with a higher version. So in end, the behavior of running appropriate migrations is correct. Sorry, but I'm out of ideas regarding your problem!

**Comment by Informaticore** [comment] 2015-07-24 16:06
But the problem isn't to create a new database, its to update from a version to a newer version while in this versions a new model was added and later some columns are added.

DBFlow does the creation of the model and the related table without versioned create table. The table will be created with all its columns befor the migrations.

I try to explain it with an example:
Version 2: the database like it is
Version 3: added model Queen (you do not need a version for this! you can just add a model and leave the version at 2, the table will be created)
Version 4: added column to Queen

If you update from version 2 to 4 it will crash because the table Queen will be created with all columns like in version 4. That means the column which will be added in the migration already exists.

How it should be:
Version 3: create model based on a version via migration!! 
Version 4: add column

So the update from 2 to 4 will run the migrations like it does in DBFlow but will create the Table for Queen in a migration, based on the version and without the columns which will be added in the next migration of version 4.

A solution would be an annotation variable for the added Queen columns.

@Column(name = "name", version = 4)

**Comment by agrosner** [comment] 2015-08-20 23:05
its all about how you choose to do the migration. Yes on app launch when database is opened, it will run create table on all tables if they don't exist. I see what you're saying is that a table is created before the migrations are run, the migrations run with the table already have those columns?

**Comment by Informaticore** [comment] 2015-09-16 10:17
>I see what you're saying is that a table is created before the migrations are run, the migrations run with the table already have those columns?

Yes!

**Comment by slesinskik** [comment] 2015-09-30 14:02
Is there any workaround for it or do we need to create immutable, version-specific tables, i.e. UsersV1, UsersV2, etc, and handle migration manually?

**Comment by WarrenFaith** [comment] 2016-03-23 13:13
I have the same issue, my new table is created before the migration runs which adds an already there column.
Is there a workaround or a best practice because you said "its all about how you choose to do the migration".
Worst case for us would be to write the onUpgrade method with raw sql statemens ourself. So any tip or help is highly appreciated!

**Comment by fabiendem** [comment] 2016-04-01 13:31
Same issue here. Though I am using DBFlow 2.2.1.
Do we know if it will be fixed in DBFlow 3.x.x?

Alternative is to write the migration yourself, but by adding the column only if it's not there...
Either via raw SQL, either by overriding:
```
@Override
public void migrate(SQLiteDatabase database) {}
```

**Comment by zoopolitic** [comment] 2016-04-07 19:07
I'm using 3.0.0-beta5 and still encounter this issue, any updates?

**Comment by zoopolitic** [comment] 2016-04-07 19:18
@agrosner something like this:

>     private boolean hasColumn(String columnName) {
>         return new User_Adapter(null).getCreationQuery().contains(columnName);
>     }

and then:

>     @Override
>     public void onPreMigrate() {
>         super.onPreMigrate();
>         if (!hasColumn("newColumn")) {
>             addColumn(SQLiteType.INTEGER, "newColumn");
>         }
> }

will it work ?

**Comment by zoopolitic** [comment] 2016-04-11 08:15
maybe we could wrap it with try/catch?

**Comment by WarrenFaith** [comment] 2016-04-11 08:22
We have done that.

We took the sources from `AlterTableMigration` and wrapped the call in a try/catch. Our catch is a bit more complex as we only want to catch the duplicate column name error:

`    @Override
    public final void migrate(SQLiteDatabase database) {
        // "ALTER TABLE "
        String sql = getAlterTableQueryBuilder().getQuery();
        String tableName = FlowManager.getTableName(table);

        // "{oldName}  RENAME TO {newName}"
        // Since the structure has been updated already, the manager knows only the new name.
        if (renameQuery != null) {
            String renameQuery = new QueryBuilder(sql).appendQuoted(oldTableName)
                    .append(this.renameQuery.getQuery())
                    .appendQuoted(tableName)
                    .toString();
            database.execSQL(renameQuery);
        }

        // We have column definitions to add here
        // ADD COLUMN columnName {type}
        if (columnDefinitions != null) {
            sql = new QueryBuilder(sql).appendQuoted(tableName).toString();
            for (QueryBuilder columnDefinition : columnDefinitions) {
                try {
                    database.execSQL(sql + " ADD COLUMN " + columnDefinition.getQuery());
                } catch (SQLiteException e) {
                    final Throwable cause = e.getCause();
                    boolean validException = false;
                    if (cause != null) {
                        final String message = cause.getMessage();
                        Log.w("Migration", message, cause);
                        if (!TextUtils.isEmpty(message) && message.contains("duplicate column name")) {
                            validException = true;
                        }
                    }
                    if (!validException) {
                        Log.w("Migration", e.getMessage(), e);
                        throw e;
                    }
                }
            }
        }
    }`

**Comment by zoopolitic** [comment] 2016-04-11 09:51
@WarrenFaith Thanks, I also replaced AlterTableMigrations with BaseMigration and simply check if columns already exists:

>     public static void addColumnSafe(DatabaseWrapper database, String tableName, String columnName, String columnType) {
>         String[] colNames = DBUtils.getColumnNames(database, tableName);
>         if (colNames == null) {
>             Timber.e("Column names is null");
>             return;
>         }
>         if (!DBUtils.hasColumn(colNames, columnType)) {
>             try {
>                 database.execSQL("ALTER TABLE `" + tableName + "` ADD COLUMN `" + columnName + "` " + columnType);
>             } catch (Exception e) {
>                 Timber.e("Error adding column " + columnName + ". Message: " + e.getMessage());
>             }
>         }
>     }
> 
>     private static String[] getColumnNames(DatabaseWrapper database, String tableName) {
>         if (database == null) {
>             return null;
>         }
>         Cursor cursor = database.rawQuery("SELECT * FROM " + tableName + " LIMIT 1", null);
>         return cursor == null ? null : cursor.getColumnNames();
>     }
> 
>     public static boolean hasColumn(String[] colNames, String column) {
>         if (colNames == null || column == null) {
>             return false;
>         }
>         for (String col : colNames) {
>             if (column.equals(col)) {
>                 return true;
>             }
>         }
>         return false;
>     }

**Comment by fabiendem** [comment] 2016-04-11 10:04
I am using something similar to @zoopolitic code.

You can simplify your hasColumn with:
```
cursor.getColumnIndex(column) != -1;
```

**Comment by zoopolitic** [comment] 2016-04-11 10:19
@fabiendem Thanks, it looks better now

**Comment by agrosner** [comment] 2016-04-24 16:24
I think the issue is that SQLite doesn't support `ADD COLUMN {columName} IF NOT EXISTS` and the fact that we execute migrations `onCreate()` and `onUpdate()` for `BaseDatabaseHelper`. So its possible that it executes twice.

**Comment by agrosner** [comment] 2016-04-24 16:25
Is that what you're seeing in these instances, that its executed twice?

**Comment by WarrenFaith** [comment] 2016-04-27 09:17
The problem is the following use case:

1. User is on scheme version X.
2. Dev creates new table in version Y. Releases the app.
3. User does not update.
4. Dev adds column to table in version Z. Adds "add column" migration and releases the app.
5. User updates

Now while updating the database, DBFlow creates the new table first, and tries afterwards to apply the "add column" migration introduced in version Z.

So the only real fix for that case would be to check if the table already has that column and if so, skip the "add column" migration.

**Comment by zoopolitic** [comment] 2016-04-27 13:57
Yep, @WarrenFaith is right

**Comment by agrosner** [comment] 2016-05-04 19:11
new snippet of code should work very well :):
```java
Cursor cursorToCheckColumnFor = SQLite.select().from(table).limit(0).query();
            if (cursorToCheckColumnFor != null) {
                try {
                    sql = new QueryBuilder(sql).append(tableName).toString();
                    for (int i = 0; i < columnDefinitions.size(); i++) {
                        QueryBuilder columnDefinition = columnDefinitions.get(i);
                        String columnName = QueryBuilder.stripQuotes(columnNames.get(i));
                        if (cursorToCheckColumnFor.getColumnIndex(columnName) == -1) {
                            database.execSQL(sql + " ADD COLUMN " + columnDefinition.getQuery());
                        }
                    }
                } finally {
                    cursorToCheckColumnFor.close();
                }
            }
```

**Comment by agrosner** [comment] 2016-05-04 19:11
in `develop`

**Closed by agrosner** 2016-05-04 19:11 UTC
Labels: enhancement, question

**Comment by lawonga** [comment] 2017-06-27 19:10
Running into this issue for .sql migration files. Any solutions for that?
