### ISSUE TITLE
Database can not copy from assets directory

### ISSUE THREAD

**Issue by Misikir** [Raizlabs/DBFlow#867] opened 2016-06-15 16:45 UTC
DBFlow Version: **3.0.1**
Issue Kind (Bug, Question, Feature): **Question**

Description:  can not copy database from  Entrance\app\src\main\assets directory 
i saw https://github.com/Raizlabs/DBFlow/issues/74 and tried it but it did n't work for me 
**Please help me out**

**Comment by ademar111190** [comment] 2016-06-18 14:37
I'm getting the same problem. I attach here a simple project that reproduces the problem
[TestDbflow.tar.gz](https://github.com/Raizlabs/DBFlow/files/321765/TestDbflow.tar.gz)

after the first run of sample app I get in emulator:
```
# pwd
/data/data/ademar.testdbflow/databases
# ls
app.db
app.db-journal
# sqlite3 app.db
SQLite version 3.8.10.2 2015-05-20 18:17:19
Enter ".help" for usage hints.
sqlite>
sqlite> .table
android_metadata  test
sqlite> .schema test
CREATE TABLE `test`(`id` INTEGER PRIMARY KEY AUTOINCREMENT,`name` TEXT);
sqlite> select count(*) from test;
0
```

the `app.db` in assets folder has 2 items in its test table, if I run the same commands on my laptop you can see:
```
$ pwd
/home/ademar/Workspace/TestDbflow/app/src/main/assets
$ ls
app.db
$ sqlite3 app.db 
SQLite version 3.13.0 2016-05-18 10:57:30
Enter ".help" for usage hints.
sqlite> 
sqlite> .table
test
sqlite> .schema test
CREATE TABLE `test` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL
);
sqlite> select count(*) from test;
2
```

**Comment by ealanhill** [comment] 2016-06-27 15:35
@agrosner 

So, I did a little investigating into this issue and this might be some unintended behavior with the library.

### Short Version
DBFlow always thinks the database file exists when it is trying to copy the database file from the assets folder to the database folder.

##### Temporary Solution
Manually copy the database over prior initializing the ```FlowManager```. There are several examples on the web that can help you (http://www.concretepage.com/android/android-ship-sqlite-database-with-apk-copy-sqlite-database-from-assets-folder-to-data-example) or you can look at ```DatabaseHelperDelegate.restoreDatabase()``` in DBFlow.

---
### Long Version
The issue seems to be with ```FlowSQLiteOpenHelper``` inheriting from ```SQLiteOpenHelper```. During the initialization of the DBFlow ```FlowManager```, a call is made to ```DatabaseHelperDelegate.performRestoreFromBackup()``` via [line 253 in FlowManager.java](https://github.com/Raizlabs/DBFlow/blob/889f2c0e3c0040833a46421ac8783ee17f5a4c28/dbflow/src/main/java/com/raizlabs/android/dbflow/config/FlowManager.java#L251-L254) which in turn calls ```DatabaseDefinition.OpenHelper()```. This function will create a new ```FlowSQLiteOpenHelper``` if one doesn't exist (which shouldn't during the initial loading of a database. It is in this function that [```DatabaseHelperDelegate.performRestoreFromBackup()```](https://github.com/Raizlabs/DBFlow/blob/889f2c0e3c0040833a46421ac8783ee17f5a4c28/dbflow/src/main/java/com/raizlabs/android/dbflow/config/DatabaseDefinition.java#L216) is called.

Now, so far the database has not been created for the app yet. However, the first line of [```DatabaseHelperDelegate.performRestoreFromBackup()```](https://github.com/Raizlabs/DBFlow/blob/889f2c0e3c0040833a46421ac8783ee17f5a4c28/dbflow/src/main/java/com/raizlabs/android/dbflow/structure/database/DatabaseHelperDelegate.java#L44-L47) calls ```getWritableDatabase()```. This ends up calling the ```FlowSQLiteOpenHelper.getDatabase()``` method which calls [```SQLiteOpenHelper.getWriteableDatabase()```](https://github.com/Raizlabs/DBFlow/blob/889f2c0e3c0040833a46421ac8783ee17f5a4c28/dbflow/src/main/java/com/raizlabs/android/dbflow/structure/database/FlowSQLiteOpenHelper.java#L51-L57) method. As a result, the [Android API](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html#getWritableDatabase()) creates the database before the DBFlow library can copy the database from the assets directory. This causes [```dbPath.exists()```](https://github.com/Raizlabs/DBFlow/blob/889f2c0e3c0040833a46421ac8783ee17f5a4c28/dbflow/src/main/java/com/raizlabs/android/dbflow/structure/database/DatabaseHelperDelegate.java#L112-L115) to always evaluate to ```true```.

##### Solution
I'm not sure at the moment, possibly removing the checks for ```dbPath.exists()``` in ```DatabaseHelperDelegate.movePrepackagedDB(...)``` method, or allowing for a way to force the move in the same method?

**Comment by Misikir** [comment] 2016-06-30 06:21
**Working solution for me**

- simply change the version dbflow_version = "**3.0.0-beta6**"  
- check the old database first with dbflow models like id, primary key , unique key, data type

and it works for me now

**Comment by agrosner** [comment] 2016-07-02 17:39
fixed in `develop. will be part of 3.1.0

**Closed by agrosner** 2016-07-02 17:39 UTC
