### ISSUE TITLE
Ifound an error

### ISSUE THREAD

**Issue by superyfwy** [Raizlabs/DBFlow#371] opened 2015-08-26 07:00 UTC
I found an error:
  java.lang.IllegalArgumentException: You can not call this method for a table that has no caching id Eitheruse one Primary Key or call convertToList ().

If the primary key using the "autoincrement = true" exception occurs, if you do not use autoincrement would normally.

@Table(databaseName = AppDatabase.NAME)
public class BModel extends BaseCacheableModel {

    @Column
    @PrimaryKey(autoincrement = true)
    long id;

    @Column
    @NotNull
    String name;

    @Column
    String sex;

    @Column
    int age;

}

**Comment by agrosner** [comment] 2015-08-26 23:16
This appears to be duplicate of #373 , closing it. If its not please reopen.

**Closed by agrosner** 2015-08-26 23:16 UTC
