### ISSUE TITLE
different users how to create a different database

### ISSUE THREAD

**Issue by ybADMIN** [Raizlabs/DBFlow#683] opened 2016-03-09 12:09 UTC
Hello agrosner, different users how to create a different database, I recently looked at DBFlow

**Comment by agrosner** [comment] 2016-04-19 03:31
this appears to be duplicate of #203 #702

**Closed by agrosner** 2016-04-19 03:31 UTC

**Comment by ybADMIN** [comment] 2016-04-20 02:50
Thank you very much for taking the time to answer my questions.
