### ISSUE TITLE
 FlowManager.getDatabase(Db.class).reset() not recreate database

### ISSUE THREAD

**Issue by PingForward** [Raizlabs/DBFlow#1089] opened 2016-11-29 04:17 UTC
DBFlow Version: 4.0.0-beta2
Bug

Description: 
` FlowManager.getDatabase(AppDatabase.class).reset(getApplicationContext());`

**I expected to reset my database (delete all data, and reopen it for new transactions).** 
So all data is deleted when I call this method but database file not created again.
I tried to call 
```
FlowManager.init(new FlowConfig.Builder(context)
                .openDatabasesOnInit(true).build());
```
but no effect.
And if a new transaction happen I got this message:
`java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.`

any help?

**Comment by trevjonez** [comment] 2016-11-29 16:36
duplicate of https://github.com/Raizlabs/DBFlow/issues/925 ?

**Comment by agrosner** [comment] 2016-12-11 14:35
in `develop` fix for #925

**Closed by agrosner** 2016-12-11 14:35 UTC

**Comment by CapnSpellcheck** [comment] 2017-10-22 20:46
Just to be clear. After executing `FlowManager.getDatabase("Main").reset(this)` we should execute whatever we did to initialize the database in the Application class?

```
        val fc = FlowConfig.Builder(this)
            .addDatabaseConfig(DatabaseConfig.Builder(Database::class.java).build())
            .build()
        FlowManager.init(fc)
```
