### ISSUE TITLE
Need to include android-maven plugin for jitpack

### ISSUE THREAD

**Issue by grennis** [Raizlabs/DBFlow#559] opened 2016-01-18 14:16 UTC
Jitpack appears to have made a chance which now requires the use of android-maven plugin for the dbflow project (not the other 2 libraries, however). See https://jitpack.io/docs/ANDROID/

**Comment by agrosner** [comment] 2016-01-18 15:41
it works as intended.(https://jitpack.io/com/github/Raizlabs/DBFlow/2110759b66/build.log). closing

**Closed by agrosner** 2016-01-18 15:41 UTC
