### ISSUE TITLE
Qualify column name in SELECT statment??

### ISSUE THREAD

**Issue by marwfair** [Raizlabs/DBFlow#545] opened 2016-01-15 21:02 UTC
I am trying to use the JOIN query, but I am getting an "ambiguous column name: id" error. I am guessing this is because I am selecting the "id" column of a table, and every one of my tables has an "id" column as a primary key. If I don't select the "id" field, my JOIN statement works fine. If I leave the .select() empty and let it return all of the columns, the "id" column does not have the correct ids.

Is it possible to qualify my column names in the select statement with the table name?

It is currently:
SQLite.select(MyTable_Table.id).from(MyTable.class)....

I would need to do something like this:
SQLite.select(MyTable.MyTable_Table.id).from(MyTable.class)....

**Comment by shanrod220** [comment] 2016-01-16 08:17
You would have to use 
SQLite.select(MyTable_Table.id.withTable()).from(MyTable.class)...
but the problem is that the withTable() call is currently broken as per my tests. Submitted a pull request for the same but it might take a while to be approved

**Comment by marwfair** [comment] 2016-01-18 15:21
Awesome, thanks! I hope this will get fixed soon.

**Comment by shanrod220** [comment] 2016-01-18 17:22
@marwfair Its fixed in the develop branch

**Closed** 2016-01-18 17:50 UTC

**Comment by marwfair** [comment] 2016-01-18 17:51
@shanrod220 Thank you!

**Comment by e-Joe** [comment] 2017-10-05 14:34
IProperty prop = (MyTable_Table.id.withTable()).from(MyTable.class);

and I get this error: cannot find symbol method from(Class<MyTable>)]]any help?

**Comment by e-Joe** [comment] 2017-10-05 14:35
I use DbFlow 3.1.1 .
