### ISSUE TITLE
Connecting to Existing DB Problems

### ISSUE THREAD

**Issue by ealanhill** [Raizlabs/DBFlow#877] opened 2016-06-23 15:11 UTC
DBFlow Version:
Issue Kind (Bug, Question, Feature): Question

Description: 

I am trying to use DBFlow with an existing database. I have installed DBFlow correctly (ie, I am able to create a database, table and add a row to the table in the database); however, I am unable to read the tables in the existing database. I put the DB in app/src/main/assets directory and ensured it has the ".db" extension.

1. Did I put the existing DB in the correct location?
2. How can I verify DBFlow loaded the existing DB?
3. What is the most verbose logging level I can set ```FlowLog``` to?

**Comment by agrosner** [comment] 2016-06-25 15:14
this is a dupe of #867

**Closed by agrosner** 2016-06-25 15:14 UTC
